# Generated by Django 3.1.2 on 2020-10-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('isbn', models.DecimalField(decimal_places=0, max_digits=13)),
                ('num_pages', models.PositiveSmallIntegerField()),
                ('cover_link', models.URLField()),
                ('language', models.CharField(max_length=30)),
            ],
        ),
    ]
