# Generated by Django 3.1.2 on 2020-10-16 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_books', '0004_auto_20201016_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pub_date',
        ),
    ]
